apiVersion: v1
kind: Namespace
metadata:
  name: websocket-ingress

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: websocket-service
  namespace: websocket-ingress
  labels:
    app: websocket-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: websocket-service
  template:
    metadata:
      labels:
        app: websocket-service
    spec:
      containers:
      - name: tcc3-websocket
        image: tcc3-websocket:latest
        imagePullPolicy: Never
        ports:
        - containerPort: 8081
        resources:
          requests:
            memory: "64Mi"
            cpu: "100m"
          limits:
            memory: "128Mi"
            cpu: "200m"
        readinessProbe:
          httpGet:
            path: /health
            port: 8081
          initialDelaySeconds: 5
          periodSeconds: 10
        livenessProbe:
          httpGet:
            path: /health
            port: 8081
          initialDelaySeconds: 15
          periodSeconds: 20

---
apiVersion: v1
kind: Service
metadata:
  name: websocket-service
  namespace: websocket-ingress
spec:
  selector:
    app: websocket-service
  ports:
  - port: 8081
    targetPort: 8081
  type: ClusterIP

---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: websocket-ingress
  namespace: websocket-ingress
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
    nginx.ingress.kubernetes.io/proxy-read-timeout: "3600"
    nginx.ingress.kubernetes.io/proxy-send-timeout: "3600"
    nginx.ingress.kubernetes.io/websocket-services: "websocket-service"
spec:
  ingressClassName: nginx
  rules:
  - http:
      paths:
      - path: /websocket
        pathType: Prefix
        backend:
          service:
            name: websocket-service
            port:
              number: 8081 