apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-apigw-tcp-conf
  namespace: tcp

data:
  nginx.conf: |
    events {}
    stream {
        server {
            listen 9000;
            proxy_pass tcp-echo.tcp.svc.cluster.local:9000;
        }
    } 