apiVersion: v1
kind: Service
metadata:
  name: nginx-apigw-tcp
  namespace: tcp
spec:
  type: NodePort
  ports:
    - name: tcp
      port: 9000
      targetPort: 9000
      nodePort: 30901
  selector:
    app: nginx-apigw-tcp 