apiVersion: v1
kind: ConfigMap
metadata:
  name: tcp-services
  namespace: ingress-nginx
  labels:
    app.kubernetes.io/name: ingress-nginx
    app.kubernetes.io/part-of: ingress-nginx
    app.kubernetes.io/component: controller
    app.kubernetes.io/managed-by: kubectl
    app.kubernetes.io/instance: ingress-nginx
    app.kubernetes.io/version: "1.10.1"
data:
  "9000": "grpc/grpc-echo:9000" 