kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
nodes:
  - role: control-plane
    extraPortMappings:
      - containerPort: 80
        hostPort: 8080
        protocol: TCP
      - containerPort: 443
        hostPort: 8443
        protocol: TCP
      - containerPort: 30082
        hostPort: 30082
        protocol: TCP
      - containerPort: 30443
        hostPort: 30443
        protocol: TCP
      - containerPort: 30901
        hostPort: 30901
        protocol: TCP
      - containerPort: 30900
        hostPort: 30900
        protocol: TCP
      - containerPort: 30902
        hostPort: 30902
        protocol: TCP 