apiVersion: v1
kind: ConfigMap
metadata:
  name: graphql-api-gateway-config
data:
  nginx.conf: |
    events {
        worker_connections 1024;
    }

    http {
        upstream graphql_backend {
            server graphql-service:8080;
            keepalive 32;
        }

        # Rate limiting
        limit_req_zone $binary_remote_addr zone=graphql_limit:10m rate=10r/s;

        # GraphQL specific settings
        map $request_method $is_query {
            default 0;
            GET 1;
            POST 1;
        }

        server {
            listen 80;
            server_name _;

            # Health check endpoint
            location /health {
                access_log off;
                return 200 'healthy\n';
            }

            location /graphql/ {
                # Rate limiting
                limit_req zone=graphql_limit burst=20 nodelay;
                limit_req_status 429;

                # GraphQL proxy settings
                proxy_pass http://graphql_backend;
                proxy_http_version 1.1;
                proxy_set_header Host $host;
                proxy_cache_bypass $http_upgrade;
                proxy_set_header X-Real-IP $remote_addr;
                proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
                proxy_set_header X-Forwarded-Proto $scheme;

                # GraphQL specific headers
                proxy_set_header Content-Type "application/json";
                proxy_set_header Accept "application/json";

                # Custom headers
                add_header X-Service-Type "GraphQL" always;
                add_header X-Protocol "GraphQL/1.1" always;

                # Circuit breaker
                proxy_next_upstream error timeout http_500 http_502 http_503 http_504;
                proxy_next_upstream_tries 3;
                proxy_next_upstream_timeout 10s;

                # Timeouts
                proxy_connect_timeout 30s;
                proxy_send_timeout 1800s;
                proxy_read_timeout 1800s;

                # Buffer settings
                proxy_buffer_size 128k;
                proxy_buffers 4 256k;
                proxy_busy_buffers_size 256k;

                # GraphQL specific settings
                client_max_body_size 8m;
                client_body_buffer_size 128k;

                # Logging
                access_log /var/log/nginx/graphql_access.log combined buffer=512k flush=1m;
                error_log /var/log/nginx/graphql_error.log warn;

                # GraphQL introspection protection
                if ($is_query = 0) {
                    return 405;
                }
            }
        }
    }
---
apiVersion: v1
kind: Namespace
metadata:
  name: graphql-gateway

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: graphql-service
  namespace: graphql-gateway
spec:
  replicas: 1
  selector:
    matchLabels:
      app: graphql-service
  template:
    metadata:
      labels:
        app: graphql-service
    spec:
      containers:
      - name: tcc3-graphql
        image: tcc3-graphql:latest
        imagePullPolicy: Never
        ports:
        - containerPort: 8082
        resources:
          requests:
            memory: "64Mi"
            cpu: "100m"
          limits:
            memory: "128Mi"
            cpu: "200m"

---
apiVersion: v1
kind: Service
metadata:
  name: graphql-service
  namespace: graphql-gateway
spec:
  selector:
    app: graphql-service
  ports:
  - port: 8082
    targetPort: 8082
  type: ClusterIP

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: graphql-api-gateway
spec:
  replicas: 2
  selector:
    matchLabels:
      app: graphql-api-gateway
  template:
    metadata:
      labels:
        app: graphql-api-gateway
    spec:
      containers:
      - name: nginx
        image: nginx:1.25
        ports:
        - containerPort: 80
        resources:
          requests:
            cpu: "100m"
            memory: "128Mi"
          limits:
            cpu: "500m"
            memory: "256Mi"
        readinessProbe:
          httpGet:
            path: /health
            port: 80
          initialDelaySeconds: 5
          periodSeconds: 10
        livenessProbe:
          httpGet:
            path: /health
            port: 80
          initialDelaySeconds: 15
          periodSeconds: 20
        volumeMounts:
        - name: nginx-config
          mountPath: /etc/nginx/nginx.conf
          subPath: nginx.conf
      volumes:
      - name: nginx-config
        configMap:
          name: graphql-api-gateway-config
---
apiVersion: v1
kind: Service
metadata:
  name: graphql-api-gateway
spec:
  type: ClusterIP
  ports:
  - port: 80
    targetPort: 80
    name: http
  selector:
    app: graphql-api-gateway 