apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-apigw-config
  namespace: http
  labels:
    app: nginx-apigw
  
data:
  nginx.conf: |
    events {}
    http {
        server {
            listen 80;
            server_name apigw.localtest.me;

            location / {
                proxy_pass http://http-echo.http.svc.cluster.local:8081/;
                proxy_set_header Host $host;
                proxy_set_header X-Real-IP $remote_addr;
                proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
                proxy_set_header X-Forwarded-Proto $scheme;
            }
        }
    } 