apiVersion: v1
kind: Service
metadata:
  name: nginx-apigw
  namespace: http
  labels:
    app: nginx-apigw
spec:
  type: NodePort
  selector:
    app: nginx-apigw
  ports:
    - name: http
      port: 80
      targetPort: 80
      nodePort: 30082