apiVersion: apps/v1
kind: Deployment
metadata:
  name: https-echo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: https-echo
  template:
    metadata:
      labels:
        app: https-echo
    spec:
      containers:
      - name: http-echo
        image: hashicorp/http-echo
        args:
          - "-listen=:8081"
          - "-text=Hello from HTTPS"
        ports:
          - containerPort: 8081
        resources:
          requests:
            cpu: "10m"
            memory: "32Mi"
          limits:
            cpu: "100m"
            memory: "128Mi"
---
apiVersion: v1
kind: Service
metadata:
  name: https-echo
spec:
  selector:
    app: https-echo
  ports:
    - protocol: TCP
      port: 8081
      targetPort: 8081 