apiVersion: v1
kind: Service
metadata:
  name: nginx-apigw
  namespace: https
  labels:
    app: nginx-apigw
spec:
  type: NodePort
  selector:
    app: nginx-apigw
  ports:
    - name: https
      port: 443
      targetPort: 443
      nodePort: 30443 