apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-apigw-conf
  namespace: grpc
  labels:
    app: nginx-apigw
data:
  nginx.conf: |
    events {}
    http {
        server {
            listen 50551 http2;
            server_name grpc.localtest.me;

            location / {
                grpc_pass grpc://grpc-echo:9000;
                grpc_set_header Host $host;
                grpc_set_header X-Real-IP $remote_addr;
            }
        }
    } 