apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-apigw-conf
  namespace: grpc

data:
  nginx.conf: |
    events {}
    http {
        server {
            listen 50551 http2;
            server_name grpc.localtest.me;

            location / {
                grpc_pass grpc://grpc-echo.grpc.svc.cluster.local:9000;
            }
        }
    } 