apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-apigw
  namespace: grpc
  labels:
    app: nginx-apigw
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx-apigw
  template:
    metadata:
      labels:
        app: nginx-apigw
    spec:
      containers:
        - name: nginx-apigw
          image: nginx:1.25-alpine
          resources:
            requests:
              cpu: "10m"
              memory: "32Mi"
            limits:
              cpu: "100m"
              memory: "128Mi"
          ports:
            - containerPort: 50551
          volumeMounts:
            - name: nginx-conf
              mountPath: /etc/nginx/nginx.conf
              subPath: nginx.conf
      volumes:
        - name: nginx-conf
          configMap:
            name: nginx-apigw-conf 