apiVersion: v1
kind: Namespace
metadata:
  name: tcp-ingress

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: tcp-service
  namespace: tcp-ingress
  labels:
    app: tcp-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: tcp-service
  template:
    metadata:
      labels:
        app: tcp-service
    spec:
      containers:
      - name: tcc3-tcp
        image: tcc3-tcp:latest
        imagePullPolicy: Never
        ports:
        - containerPort: 8083
        resources:
          requests:
            memory: "64Mi"
            cpu: "100m"
          limits:
            memory: "128Mi"
            cpu: "200m"
        readinessProbe:
          tcpSocket:
            port: 8083
          initialDelaySeconds: 5
          periodSeconds: 10
        livenessProbe:
          tcpSocket:
            port: 8083
          initialDelaySeconds: 15
          periodSeconds: 20

---
apiVersion: v1
kind: Service
metadata:
  name: tcp-service
  namespace: tcp-ingress
spec:
  selector:
    app: tcp-service
  ports:
  - port: 8083
    targetPort: 8083
  type: ClusterIP

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: tcp-services
  namespace: ingress-nginx
data:
  "30000": "tcp-ingress/tcp-service:8083" 