apiVersion: v1
kind: Namespace
metadata:
  name: graphql-ingress

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: graphql-service
  namespace: graphql-ingress
  labels:
    app: graphql-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: graphql-service
  template:
    metadata:
      labels:
        app: graphql-service
    spec:
      containers:
      - name: tcc3-graphql
        image: tcc3-graphql:latest
        imagePullPolicy: Never
        ports:
        - containerPort: 8082
        resources:
          requests:
            memory: "64Mi"
            cpu: "100m"
          limits:
            memory: "128Mi"
            cpu: "200m"
        readinessProbe:
          httpGet:
            path: /health
            port: 8082
          initialDelaySeconds: 5
          periodSeconds: 10
        livenessProbe:
          httpGet:
            path: /health
            port: 8082
          initialDelaySeconds: 15
          periodSeconds: 20

---
apiVersion: v1
kind: Service
metadata:
  name: graphql-service
  namespace: graphql-ingress
spec:
  selector:
    app: graphql-service
  ports:
  - port: 8082
    targetPort: 8082
  type: ClusterIP

---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: graphql-ingress
  namespace: graphql-ingress
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  ingressClassName: nginx
  rules:
  - http:
      paths:
      - path: /graphql
        pathType: Prefix
        backend:
          service:
            name: graphql-service
            port:
              number: 8082 