apiVersion: v1
kind: Service
metadata:
  name: ingress-nginx-grpc
  namespace: ingress-nginx
spec:
  type: NodePort
  ports:
    - name: grpc
      port: 9000
      targetPort: 9000
      nodePort: 30900
  selector:
    app.kubernetes.io/component: controller
    app.kubernetes.io/instance: ingress-nginx
    app.kubernetes.io/name: ingress-nginx
---
apiVersion: v1
kind: Service
metadata:
  name: ingress-nginx-tcp
  namespace: ingress-nginx
spec:
  type: NodePort
  ports:
    - name: tcp
      port: 9002
      targetPort: 9002
      nodePort: 30902
  selector:
    app.kubernetes.io/component: controller
    app.kubernetes.io/instance: ingress-nginx
    app.kubernetes.io/name: ingress-nginx 