apiVersion: v1
kind: Namespace
metadata:
  name: https-ingress

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: https-service
  namespace: https-ingress
  labels:
    app: https-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: https-service
  template:
    metadata:
      labels:
        app: https-service
    spec:
      containers:
      - name: tcc3-https
        image: tcc3-https:latest
        imagePullPolicy: Never
        ports:
        - containerPort: 8443
        resources:
          requests:
            memory: "64Mi"
            cpu: "100m"
          limits:
            memory: "128Mi"
            cpu: "200m"
        volumeMounts:
        - name: ssl-certs
          mountPath: /app/certs
          readOnly: true
        readinessProbe:
          httpGet:
            path: /health
            port: 8443
            scheme: HTTPS
          initialDelaySeconds: 5
          periodSeconds: 10
        livenessProbe:
          httpGet:
            path: /health
            port: 8443
            scheme: HTTPS
          initialDelaySeconds: 15
          periodSeconds: 20
      volumes:
      - name: ssl-certs
        secret:
          secretName: ssl-certs

---
apiVersion: v1
kind: Service
metadata:
  name: https-service
  namespace: https-ingress
spec:
  selector:
    app: https-service
  ports:
  - port: 8443
    targetPort: 8443
  type: ClusterIP

---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: https-ingress
  namespace: https-ingress
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
    nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
spec:
  ingressClassName: nginx
  tls:
  - hosts:
    - localhost
    secretName: https-secret
  rules:
  - host: localhost
    http:
      paths:
      - path: /https
        pathType: Prefix
        backend:
          service:
            name: https-service
            port:
              number: 8443 