apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-apigw-ws-conf
  namespace: websocket
  labels:
    app: nginx-apigw-ws
data:
  nginx.conf: |
    events {}
    http {
      map $http_upgrade $connection_upgrade {
        default upgrade;
        '' close;
      }

      server {
        listen 80;
        server_name websocket.localtest.me;

        location / {
          proxy_pass http://websocket-echo:9000;
          proxy_http_version 1.1;
          proxy_set_header Upgrade $http_upgrade;
          proxy_set_header Connection $connection_upgrade;
          proxy_set_header Host $host;
          proxy_set_header X-Real-IP $remote_addr;
        }
      }
    } 