apiVersion: v1
kind: ConfigMap
metadata:
  name: websocket-api-gateway-config
data:
  nginx.conf: |
    events {
        worker_connections 1024;
    }

    http {
        upstream websocket_backend {
            server websocket-service:8080;
            keepalive 32;
        }

        # Rate limiting
        limit_req_zone $binary_remote_addr zone=websocket_limit:10m rate=10r/s;

        server {
            listen 80;
            server_name _;

            # Health check endpoint
            location /health {
                access_log off;
                return 200 'healthy\n';
            }

            location /ws/ {
                # Rate limiting
                limit_req zone=websocket_limit burst=20 nodelay;
                limit_req_status 429;

                # WebSocket proxy settings
                proxy_pass http://websocket_backend;
                proxy_http_version 1.1;
                proxy_set_header Upgrade $http_upgrade;
                proxy_set_header Connection "upgrade";
                proxy_set_header Host $host;
                proxy_cache_bypass $http_upgrade;
                proxy_set_header X-Real-IP $remote_addr;
                proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
                proxy_set_header X-Forwarded-Proto $scheme;

                # Custom headers
                add_header X-Service-Type "WebSocket" always;
                add_header X-Protocol "WebSocket/1.1" always;

                # Circuit breaker
                proxy_next_upstream error timeout http_500 http_502 http_503 http_504;
                proxy_next_upstream_tries 3;
                proxy_next_upstream_timeout 10s;

                # Timeouts
                proxy_connect_timeout 30s;
                proxy_send_timeout 1800s;
                proxy_read_timeout 1800s;

                # Buffer settings
                proxy_buffer_size 128k;
                proxy_buffers 4 256k;
                proxy_busy_buffers_size 256k;

                # WebSocket specific settings
                proxy_read_timeout 1800s;
                proxy_send_timeout 1800s;
                proxy_connect_timeout 30s;

                # Logging
                access_log /var/log/nginx/websocket_access.log combined buffer=512k flush=1m;
                error_log /var/log/nginx/websocket_error.log warn;
            }
        }
    }
---
apiVersion: v1
kind: Namespace
metadata:
  name: websocket-gateway

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: websocket-service
  namespace: websocket-gateway
spec:
  replicas: 1
  selector:
    matchLabels:
      app: websocket-service
  template:
    metadata:
      labels:
        app: websocket-service
    spec:
      containers:
      - name: tcc3-websocket
        image: tcc3-websocket:latest
        imagePullPolicy: Never
        ports:
        - containerPort: 8081
        resources:
          requests:
            memory: "64Mi"
            cpu: "100m"
          limits:
            memory: "128Mi"
            cpu: "200m"

---
apiVersion: v1
kind: Service
metadata:
  name: websocket-service
  namespace: websocket-gateway
spec:
  selector:
    app: websocket-service
  ports:
  - port: 8081
    targetPort: 8081
  type: ClusterIP

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: websocket-api-gateway
spec:
  replicas: 2
  selector:
    matchLabels:
      app: websocket-api-gateway
  template:
    metadata:
      labels:
        app: websocket-api-gateway
    spec:
      containers:
      - name: nginx
        image: nginx:1.25
        ports:
        - containerPort: 80
        resources:
          requests:
            cpu: "100m"
            memory: "128Mi"
          limits:
            cpu: "500m"
            memory: "256Mi"
        readinessProbe:
          httpGet:
            path: /health
            port: 80
          initialDelaySeconds: 5
          periodSeconds: 10
        livenessProbe:
          httpGet:
            path: /health
            port: 80
          initialDelaySeconds: 15
          periodSeconds: 20
        volumeMounts:
        - name: nginx-config
          mountPath: /etc/nginx/nginx.conf
          subPath: nginx.conf
      volumes:
      - name: nginx-config
        configMap:
          name: websocket-api-gateway-config
---
apiVersion: v1
kind: Service
metadata:
  name: websocket-api-gateway
spec:
  type: ClusterIP
  ports:
  - port: 80
    targetPort: 80
    name: http
  selector:
    app: websocket-api-gateway 